services:
  app:
    image: dancet/goodwe-esa-monitor:latest
    ports:
      - "${PORT:-8765}:8080"
    volumes:
      - goodwe-esa-monitor-data:/data
    environment:
      - INVERTER_IP=192.168.1.x
      - MODBUS_PORT=502
      - SLAVE_ID=247
      - TZ=Australia/Brisbane
    restart: unless-stopped

volumes:
  goodwe-esa-monitor-data:
